name: Delete Branch on Merge

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete branch
        run: |
          BRANCH_NAME=${{ github.event.pull_request.head.ref }}
          echo "Deleting branch: $BRANCH_NAME"
          git push origin --delete $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}